# Generated by Django 5.2.6 on 2025-09-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_stripe_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
