# Generated by Django 5.2.6 on 2025-10-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='credits',
            new_name='audio_credits_s',
        ),
        migrations.AddField(
            model_name='customuser',
            name='text_credits_ch',
            field=models.IntegerField(default=0),
        ),
    ]
