# Generated by Django 5.2.6 on 2025-09-16 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('course_markdown', models.TextField(blank=True)),
                ('qcm_markdown', models.TextField(blank=True)),
                ('exercises_markdown', models.TextField(blank=True)),
                ('audio_duration', models.IntegerField(default=0)),
                ('processing', models.BooleanField(default=False)),
                ('source_type', models.CharField(blank=True, default='', max_length=10)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
