# Generated by Django 5.2.6 on 2025-10-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='fr', max_length=5),
        ),
        migrations.AddField(
            model_name='course',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.CharField(default='PENDING', max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='transcript_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
